# Generated by Django 6.0.4 on 2026-07-08 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('content', models.TextField(verbose_name='İçerik')),
                ('date_posted', models.DateTimeField(auto_now_add=True, verbose_name='Yayınlanma Tarihi')),
            ],
            options={
                'verbose_name': 'Duyuru',
                'verbose_name_plural': 'Duyurular',
                'ordering': ['-date_posted'],
            },
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Ad')),
                ('last_name', models.CharField(max_length=50, verbose_name='Soyad')),
                ('flat_number', models.CharField(max_length=10, unique=True, verbose_name='Daire No')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-posta')),
            ],
            options={
                'verbose_name': 'Daire Sakini',
                'verbose_name_plural': 'Daire Sakinleri',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('INCOME', 'Gelir'), ('EXPENSE', 'Gider')], max_length=10, verbose_name='İşlem Tipi')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tutar')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Tarih')),
            ],
            options={
                'verbose_name': 'Gelir/Gider İşlemi',
                'verbose_name_plural': 'Gelir/Gider İşlemleri',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Due',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tutar')),
                ('issue_date', models.DateField(verbose_name='Kesim Tarihi')),
                ('due_date', models.DateField(verbose_name='Son Ödeme Tarihi')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Ödendi mi?')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dues', to='core.resident', verbose_name='Daire Sakini')),
            ],
            options={
                'verbose_name': 'Aidat',
                'verbose_name_plural': 'Aidatlar',
                'ordering': ['-issue_date'],
            },
        ),
    ]
