# Generated by Django 6.0.4 on 2026-07-08 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı Hesabı'),
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Konu / Başlık')),
                ('description', models.TextField(verbose_name='Mesaj')),
                ('status', models.CharField(choices=[('PENDING', 'Bekliyor'), ('RESOLVED', 'Çözüldü')], default='PENDING', max_length=10, verbose_name='Durum')),
                ('date_submitted', models.DateTimeField(auto_now_add=True, verbose_name='Tarih')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='core.resident', verbose_name='Daire Sakini')),
            ],
            options={
                'verbose_name': 'İstek / Şikayet',
                'verbose_name_plural': 'İstek ve Şikayetler',
                'ordering': ['-date_submitted'],
            },
        ),
    ]
