# Generated by Django 6.0.4 on 2026-07-08 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_facility_poll_transaction_receipt_booking_choice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Belge Adı')),
                ('file', models.FileField(upload_to='documents/', verbose_name='Dosya')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='Yüklenme Tarihi')),
            ],
            options={
                'verbose_name': 'Belge / Karar Defteri',
                'verbose_name_plural': 'Belgeler',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=150, verbose_name='Demirbaş Adı')),
                ('location', models.CharField(max_length=150, verbose_name='Bulunduğu Yer')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='Alım Tarihi')),
                ('warranty_end', models.DateField(blank=True, null=True, verbose_name='Garanti Bitiş')),
            ],
            options={
                'verbose_name': 'Demirbaş',
                'verbose_name_plural': 'Demirbaşlar',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Ad')),
                ('last_name', models.CharField(max_length=100, verbose_name='Soyad')),
                ('role', models.CharField(max_length=100, verbose_name='Görevi')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Maaş')),
            ],
            options={
                'verbose_name': 'Personel',
                'verbose_name_plural': 'Personeller',
            },
        ),
        migrations.CreateModel(
            name='MessageBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Mesaj')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Tarih')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.resident', verbose_name='Sakin')),
            ],
            options={
                'verbose_name': 'İlan / Mesaj',
                'verbose_name_plural': 'Mesaj Panosu',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(max_length=150, verbose_name='Ziyaretçi / Firma Adı')),
                ('visitor_type', models.CharField(choices=[('GUEST', 'Misafir'), ('CARGO', 'Kargo / Teslimat'), ('SERVICE', 'Servis / Tamir')], default='GUEST', max_length=15, verbose_name='Tipi')),
                ('arrival_time', models.DateTimeField(auto_now_add=True, verbose_name='Geliş Zamanı')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitors', to='core.resident', verbose_name='Daire Sakini')),
            ],
            options={
                'verbose_name': 'Ziyaretçi / Kargo',
                'verbose_name_plural': 'Ziyaretçi ve Kargolar',
                'ordering': ['-arrival_time'],
            },
        ),
    ]
