# Generated by Django 6.0.4 on 2026-07-08 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_document_inventory_staff_messageboard_visitor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='Firma Adı')),
                ('category', models.CharField(max_length=100, verbose_name='Kategori (Asansör, Tesisat vb.)')),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name='İlgili Kişi')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
            ],
            options={
                'verbose_name': 'Tedarikçi / Acil Durum',
                'verbose_name_plural': 'Firma ve Tedarikçiler',
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=100, verbose_name='Evcil Hayvan Adı')),
                ('pet_type', models.CharField(max_length=100, verbose_name='Türü / Cinsi')),
                ('notes', models.TextField(blank=True, verbose_name='Aşı / Özel Notlar')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='core.resident', verbose_name='Daire Sakini')),
            ],
            options={
                'verbose_name': 'Evcil Hayvan',
                'verbose_name_plural': 'Evcil Hayvanlar',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Görev Başlığı')),
                ('description', models.TextField(verbose_name='Görev Detayı')),
                ('status', models.CharField(choices=[('PENDING', 'Bekliyor'), ('IN_PROGRESS', 'Yapılıyor'), ('DONE', 'Tamamlandı')], default='PENDING', max_length=20, verbose_name='Durum')),
                ('date_assigned', models.DateTimeField(auto_now_add=True, verbose_name='Atanma Tarihi')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.staff', verbose_name='Görevli Personel')),
            ],
            options={
                'verbose_name': 'Görev / İş Emri',
                'verbose_name_plural': 'Görevler',
            },
        ),
    ]
