# Generated by Django 6.0.4 on 2026-08-22 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_supplier_pet_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Başlık')),
                ('message', models.TextField(verbose_name='Mesaj / Detay')),
                ('severity', models.CharField(choices=[('INFO', 'Bilgilendirme'), ('WARNING', 'Uyarı / Kesinti'), ('DANGER', 'Kritik Acil Durum')], default='WARNING', max_length=10, verbose_name='Önem Seviyesi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tarih')),
            ],
            options={
                'verbose_name': 'Acil Durum / Uyarı',
                'verbose_name_plural': 'Acil Durum & Kesinti Bildirimleri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='resident',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='Profil Fotoğrafı'),
        ),
        migrations.CreateModel(
            name='MarketplaceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='İlan Başlığı')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Fiyat (TL)')),
                ('item_type', models.CharField(choices=[('FOR_SALE', 'Satılık'), ('FOR_RENT', 'Kiralık'), ('FREE', 'Ücretsiz / Bağış')], default='FOR_SALE', max_length=20, verbose_name='İlan Tipi')),
                ('image', models.ImageField(blank=True, null=True, upload_to='marketplace/', verbose_name='Ürün Fotoğrafı')),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='İletişim Numarası')),
                ('is_sold', models.BooleanField(default=False, verbose_name='Satıldı / Kapandı mı?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yayın Tarihi')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_items', to='core.resident', verbose_name='İlan Sahibi')),
            ],
            options={
                'verbose_name': 'Pazar İlanı',
                'verbose_name_plural': 'Komşu Pazarı / 2. El İlanlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
